"""Add unsubscribe fields to email_recommendations

Revision ID: bba22cdfe686
Revises: 25a6f52a32f7
Create Date: 2025-11-29 21:37:15.063628+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba22cdfe686'
down_revision: Union[str, None] = '25a6f52a32f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires server_default for NOT NULL columns when table has data
    op.add_column('email_recommendations', sa.Column('has_unsubscribe', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('email_recommendations', sa.Column('unsubscribe_url', sa.Text(), nullable=True))
    op.add_column('email_recommendations', sa.Column('unsubscribe_mailto', sa.String(length=255), nullable=True))
    op.add_column('email_recommendations', sa.Column('unsubscribe_one_click', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('email_recommendations', sa.Column('user_wants_unsubscribe', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_recommendations', 'user_wants_unsubscribe')
    op.drop_column('email_recommendations', 'unsubscribe_one_click')
    op.drop_column('email_recommendations', 'unsubscribe_mailto')
    op.drop_column('email_recommendations', 'unsubscribe_url')
    op.drop_column('email_recommendations', 'has_unsubscribe')
    # ### end Alembic commands ###
