#!/usr/bin/env python3
"""
TypeScript Type Generator for Inbox Nuke

This script fetches the OpenAPI schema from the FastAPI backend and generates
TypeScript interfaces for the frontend. This ensures frontend-backend type safety.

Usage:
    python scripts/generate-types.py

The script will:
1. Fetch OpenAPI schema from http://localhost:8000/openapi.json
2. Generate TypeScript interfaces in frontend/lib/api-types.ts
3. Report any schema changes

Run this whenever you modify backend schemas.py or add new endpoints.
"""

import json
import sys
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

# Configuration
OPENAPI_URL = "http://localhost:8000/openapi.json"
OUTPUT_PATH = Path(__file__).parent.parent / "frontend" / "lib" / "api-types.ts"


def fetch_openapi_schema() -> Dict[str, Any]:
    """Fetch OpenAPI schema from running backend."""
    try:
        with urllib.request.urlopen(OPENAPI_URL, timeout=5) as response:
            return json.loads(response.read().decode())
    except Exception as e:
        print(f"Error: Could not fetch OpenAPI schema from {OPENAPI_URL}")
        print(f"       Make sure the backend is running: python main.py")
        print(f"       Details: {e}")
        sys.exit(1)


def openapi_type_to_typescript(prop: Dict[str, Any], schemas: Dict[str, Any]) -> str:
    """Convert OpenAPI type to TypeScript type."""
    # Handle non-dict props (e.g., boolean for additionalProperties: true)
    if not isinstance(prop, dict):
        return "any"

    if "$ref" in prop:
        # Reference to another schema
        ref_name = prop["$ref"].split("/")[-1]
        return ref_name

    prop_type = prop.get("type", "any")

    if prop_type == "string":
        if prop.get("format") == "date-time":
            return "string"  # ISO date string
        return "string"
    elif prop_type == "integer" or prop_type == "number":
        return "number"
    elif prop_type == "boolean":
        return "boolean"
    elif prop_type == "array":
        items = prop.get("items", {})
        item_type = openapi_type_to_typescript(items, schemas)
        return f"{item_type}[]"
    elif prop_type == "object":
        # Check for additionalProperties (Dict type)
        if "additionalProperties" in prop:
            additional = prop["additionalProperties"]
            if isinstance(additional, bool):
                return "Record<string, any>"
            value_type = openapi_type_to_typescript(additional, schemas)
            return f"Record<string, {value_type}>"
        return "Record<string, any>"
    elif prop_type == "null":
        return "null"

    # Handle anyOf/oneOf for Optional types
    if "anyOf" in prop:
        types = [openapi_type_to_typescript(t, schemas) for t in prop["anyOf"]]
        return " | ".join(types)

    return "any"


def generate_interface(name: str, schema: Dict[str, Any], schemas: Dict[str, Any]) -> str:
    """Generate a TypeScript interface from an OpenAPI schema."""
    lines = [f"export interface {name} {{"]

    properties = schema.get("properties", {})
    required = set(schema.get("required", []))

    for prop_name, prop_def in properties.items():
        ts_type = openapi_type_to_typescript(prop_def, schemas)
        optional = "" if prop_name in required else "?"

        # Add description as comment if available
        description = prop_def.get("description", "")
        if description:
            lines.append(f"  /** {description} */")

        lines.append(f"  {prop_name}{optional}: {ts_type};")

    lines.append("}")
    return "\n".join(lines)


def generate_typescript_types(schema: Dict[str, Any]) -> str:
    """Generate all TypeScript types from OpenAPI schema."""
    schemas = schema.get("components", {}).get("schemas", {})

    # Header
    lines = [
        "/**",
        " * AUTO-GENERATED TypeScript types from FastAPI backend",
        f" * Generated at: {datetime.now().isoformat()}",
        " * ",
        " * DO NOT EDIT THIS FILE MANUALLY!",
        " * Run: python scripts/generate-types.py",
        " * ",
        " * These types are generated from backend/schemas.py",
        " * Any mismatch between frontend and backend will be caught at compile time.",
        " */",
        "",
        "// ============================================================================",
        "// API Response Types",
        "// ============================================================================",
        "",
    ]

    # Generate interfaces for each schema
    for name, schema_def in sorted(schemas.items()):
        if schema_def.get("type") == "object" or "properties" in schema_def:
            interface = generate_interface(name, schema_def, schemas)
            lines.append(interface)
            lines.append("")

    # Add helper types
    lines.extend([
        "// ============================================================================",
        "// API Endpoint Types",
        "// ============================================================================",
        "",
        "/** Standard API error response */",
        "export interface ApiError {",
        "  error: string;",
        "  detail?: string;",
        "}",
        "",
        "/** Pagination parameters */",
        "export interface PaginationParams {",
        "  limit?: number;",
        "  offset?: number;",
        "}",
        "",
        "/** Generic paginated response */",
        "export interface PaginatedResponse<T> {",
        "  items: T[];",
        "  total: number;",
        "  limit: number;",
        "  offset: number;",
        "}",
        "",
    ])

    return "\n".join(lines)


def main():
    print("Fetching OpenAPI schema from backend...")
    schema = fetch_openapi_schema()

    print(f"Found {len(schema.get('components', {}).get('schemas', {}))} schemas")

    print("Generating TypeScript types...")
    typescript_code = generate_typescript_types(schema)

    # Ensure output directory exists
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Write output
    OUTPUT_PATH.write_text(typescript_code)
    print(f"Generated: {OUTPUT_PATH}")

    # Summary
    schemas = schema.get("components", {}).get("schemas", {})
    print(f"\nGenerated {len(schemas)} TypeScript interfaces:")
    for name in sorted(schemas.keys()):
        print(f"  - {name}")

    print("\nSuccess! Frontend types are now in sync with backend schemas.")
    print("Import types in your frontend code:")
    print("  import { ScoringProgressResponse, EmailScoreResponse } from '@/lib/api-types';")


if __name__ == "__main__":
    main()
